[SERVER]
HOST = 192.168.119.183
PORT = 1020

[DATABASE]
# MongoDB connection string with authentication
; MONGO_URI = mongodb://localhost:27017
MONGO_URI = mongodb://sa:963852@192.168.102.120:27017/
DATABASE_NAME = WEB_SCRAPING
DB_NAME1 = GETMASTERDATA
COLLECTION_NAME1 = MASTERDATA
MASTERDATA_URI = mongodb://sa:963852@192.168.102.120:27017/
MASTERDATA_DB = GETMASTERDATA

# SQL Server connection details
SQL_SERVER_HOST = 192.168.102.120
SQL_SERVER_DRIVER = ODBC Driver 17 for SQL Server
SQL_SERVER_PORT = 1433
SQL_SERVER_USERNAME = sa
SQL_SERVER_PASSWORD = 963852
SQL_SERVER_DATABASE_NAME = E-IPO
SQL_SERVER_TABLE_NAME = Ipo_Details_master


[PATH]
LOGGER_PATH = Logs


[NSE]
BASE_URL = https://www.nseindia.com
COOKIES_FILE = nse_cookies.json

